### ISSUE TITLE
软件建议

### ISSUE THREAD

**Issue by ShiguiHuang** [Howardzhangdqs/jumping-latex-ocr#3]
可以直接出个打包好的exe文件吗？
安装依赖环境属实麻烦和占空间。

**Comment by Howardzhangdqs** [comment]
这个项目本身就是整活的，项目依赖有Pytorch等等很重的第三方库，做成整合包大小可能也要几个G，而且工作量挺大的。这些依赖都是做机器学习常用的，如果不是做这方面的朋友我觉得就看看demo演示，从这个抽象的项目里收获快乐就好啦，因为本身这个项目就没什么实际意义 :joy:

**Comment by ShiguiHuang** [comment]
> 这个项目本身就是整活的，项目依赖有Pytorch等等很重的第三方库，做成整合包大小可能也要几个G，而且工作量挺大的。这些依赖都是做机器学习常用的，如果不是做这方面的朋友我觉得就看看demo演示，从这个抽象的项目里收获快乐就好啦，因为本身这个项目就没什么实际意义 😂

好的，谢谢老哥。
